### PR TITLE
Fix slot fetch cache lookup

### PR DESCRIPTION
**Pull request by arcz**
## Description
I think the slot fetch cache didn't work as intended because it checked `fetchedContracts` instead of `fetchedStorage`

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by arcz** [comment]
If this PR makes sense I'll add a test for it too

**Comment by d-xo** [comment]
nice catch. fix seems sensible, happy to merge once we have a test in place

**Comment by arcz** [comment]
@d-xo Test added

**Review by d-xo — APPROVED** [review]

**Comment by d-xo** [comment]
Thanks!

**Pull request merged**
