### PR TITLE
Removing unused sha3Crack

### PR DESCRIPTION
**Pull request by msooseth**
## Description
Removes the old `sha3Crack` which is collected but never used. It has been replaced with the actually used `keccakEqs`

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [x] updated the changelog

### CODE REVIEW

**Comment by d-xo** [comment]
cc @arcz do you need this in echidna?

**Comment by arcz** [comment]
Nope

**Review by d-xo — APPROVED** [review]
lgtm!

**Comment by msooseth** [comment]
Again a fuzz failure. This is likely related to the issue that's already been fixed. Can't be re-produced unfortunately due to issue that we are fixing in another PR. I am re-kicking.

```
2023-07-11T14:18:08.3574012Z hevm>     byte-simplification:                                          Unsat
2023-07-11T14:18:08.3591617Z hevm> skip
2023-07-11T14:18:08.3778361Z hevm> Unsat
2023-07-11T14:18:08.3792384Z hevm> skip
2023-07-11T14:18:08.4000860Z hevm> Unsat
2023-07-11T14:18:08.4186501Z hevm> Unsat
2023-07-11T14:18:08.4371891Z hevm> Unsat
2023-07-11T14:18:08.4553516Z hevm> Unsat
2023-07-11T14:18:08.4761241Z hevm> Unsat
2023-07-11T14:18:08.4944345Z hevm> Unsat
2023-07-11T14:18:08.5125878Z hevm> Unsat
2023-07-11T14:18:08.5138934Z hevm> skip
2023-07-11T14:18:08.5315707Z hevm> Unsat
2023-07-11T14:18:08.5536082Z hevm> Unsat
2023-07-11T14:18:08.5734006Z hevm> Unsat
2023-07-11T14:18:08.5930123Z hevm> Unsat
2023-07-11T14:18:08.6145884Z hevm> Unsat
2023-07-11T14:18:08.6341608Z hevm> Unsat
2023-07-11T14:18:08.6543829Z hevm> Unsat
2023-07-11T14:18:08.6739112Z hevm> Unsat
2023-07-11T14:18:08.6928440Z hevm> Unsat
2023-07-11T14:18:08.7118230Z hevm> Unsat
2023-07-11T14:18:08.7313824Z hevm> Unsat
2023-07-11T14:18:08.7503104Z hevm> Unsat
2023-07-11T14:18:08.7709485Z hevm> Unsat
2023-07-11T14:18:08.7889488Z hevm> Unsat
2023-07-11T14:18:08.8084100Z hevm> Unsat
2023-07-11T14:18:08.8109105Z hevm> FAIL (0.47s)
2023-07-11T14:18:08.8110571Z hevm>       *** Failed! Exception: 'TryFromException @W256 @Int 0x9ad8f9bf48200000c57b33b831400000c6b8944ceb800000fe4b8698e15 Nothing' (after 29 tests):
2023-07-11T14:18:08.8111595Z hevm>       ReadByte (Lit 0x9ad8f9bf48200000c57b33b831400000c6b8944ceb800000fe4b8698e14) (WriteByte (And (Lit 0x5c) (Lit 0x5f)) (LitByte 30) (ConcreteBuf "\196\216\183X\DC1:\214f\196\145w\234\206\161\194'\246g\DC4\191\141\RS\vc<\223\140\176cX\v\207\239"))
2023-07-11T14:18:08.8114707Z hevm>       Use --quickcheck-replay=204327 to reproduce.
2023-07-11T14:18:08.8115161Z hevm>       Use -p '/byte-simplification/' to rerun this test only.
```

**Review by arcz — APPROVED** [review]

**Pull request merged**
