### PR TITLE
Fix part of the State space leak

### PR DESCRIPTION
**Pull request by arcz**
## Description
This fixes part of the space leak that happens inside State. For the test `loopMul_d2g0v0_London` the time went down from 98s to 73s (34% improvement) on my machine.

Before:
```
 181,446,033,696 bytes allocated in the heap
  50,253,045,752 bytes copied during GC
  14,248,185,032 bytes maximum residency (20 sample(s))
   1,510,627,312 bytes maximum slop
           30034 MiB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     177075 colls, 177075 par   635.130s  24.324s     0.0001s    0.0221s
  Gen  1        20 colls,    19 par   2313.280s  100.571s     5.0285s    35.6827s

  Parallel GC work balance: 0.38% (serial 0%, perfect 100%)

  TASKS: 50 (1 bound, 49 peak workers (49 total), using -N24)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.004s  (  0.011s elapsed)
  MUT     time  221.051s  ( 75.926s elapsed)
  GC      time  2948.410s  (124.895s elapsed)
  RP      time    0.000s  (  0.000s elapsed)
  PROF    time    0.000s  (  0.000s elapsed)
  EXIT    time    0.007s  (  0.002s elapsed)
  Total   time  3169.472s  (200.833s elapsed)

  Alloc rate    820,831,648 bytes per MUT second

  Productivity   7.0% of total user, 37.8% of total elapsed
```

After:
```
 449,116,289,680 bytes allocated in the heap
   8,236,928,744 bytes copied during GC
     545,006,824 bytes maximum residency (19 sample(s))
   1,229,335,320 bytes maximum slop
            2949 MiB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     441117 colls, 441117 par   691.961s  21.302s     0.0000s    0.0264s
  Gen  1        19 colls,    18 par   97.701s   4.374s     0.2302s    0.9794s

  Parallel GC work balance: 0.83% (serial 0%, perfect 100%)

  TASKS: 50 (1 bound, 49 peak workers (49 total), using -N24)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.004s  (  0.009s elapsed)
  MUT     time  417.787s  (155.933s elapsed)
  GC      time  789.661s  ( 25.676s elapsed)
  RP      time    0.000s  (  0.000s elapsed)
  PROF    time    0.000s  (  0.000s elapsed)
  EXIT    time    0.003s  (  0.001s elapsed)
  Total   time  1207.455s  (181.619s elapsed)

  Alloc rate    1,074,987,541 bytes per MUT second

  Productivity  34.6% of total user, 85.9% of total elapsed
```

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by d-xo** [comment]
When I try to reproduce the test failures locally I very quickly run out of memory on my laptop, wondering if that's why we're seeing failures in CI? Wonder if this PR triggers a different memory leak?

**Comment by arcz** [comment]
@d-xo I still work on this, I need a bigger chunk of time to debug Stepper again

**Comment by d-xo** [comment]
looks good, just curious why this actually fixed the space leaks?

also wondering if we can enable some more of the ethereum tests in ci now?

**Comment by arcz** [comment]
Let's try, now the time tests take to run is almost halved. I'm still not sure why this fixed leak, I suspect GHC doesn't like`State.state (runState exec1)` in a tight loop and now with 9.2 it optimised even better.

**Comment by arcz** [comment]
@d-xo I enabled back test files that were disabled for CI and the test suite seems to run fine. This gives us just 15 extra tests disabled for CI (listed in `ciProblematicTests`) instead of a few hundreds.

**Comment by d-xo** [comment]
Really nice :)

**Pull request merged**
