### PR TITLE
Bump nixpkgs

### PR DESCRIPTION
**Pull request by arcz**
## Description
solc works again :)

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by d-xo** [comment]
Think this should work once https://github.com/ethereum/hevm/pull/275 is in

**Comment by d-xo** [comment]
well, we have a new error at least. looks like we're not able to invoke `evm` from `geth` anymore for some reason when doing differential fuzzing...

**Comment by msooseth** [comment]
Did this `chisel` issue pop up only here? See logs:
```
2023-06-21T14:24:10.4982119Z searching for dependencies of /nix/store/qmhhbs57x699bmmlgjgq94gijkbwkqwi-foundry-0.0.0/bin/.anvil-wrapped
2023-06-21T14:24:10.4991609Z auto-patchelf: 0 dependencies could not be satisfied
2023-06-21T14:24:10.5214846Z running install tests
2023-06-21T14:24:10.5581060Z postAutoPatchelf
2023-06-21T14:24:10.6893345Z error: unrecognized subcommand 'completions'
2023-06-21T14:24:10.6893818Z 
2023-06-21T14:24:10.6894249Z Usage: chisel [OPTIONS] [COMMAND]
2023-06-21T14:24:10.6894448Z 
2023-06-21T14:24:10.6894667Z For more information, try '--help'.
2023-06-21T14:24:10.6903314Z error: unrecognized subcommand 'completions'
2023-06-21T14:24:10.6903840Z 
2023-06-21T14:24:10.6904097Z Usage: chisel [OPTIONS] [COMMAND]
2023-06-21T14:24:10.6904402Z 
2023-06-21T14:24:10.6904872Z For more information, try '--help'.
2023-06-21T14:24:10.6905716Z error: unrecognized subcommand 'completions'
2023-06-21T14:24:10.6906041Z 
2023-06-21T14:24:10.6906554Z Usage: chisel [OPTIONS] [COMMAND]
2023-06-21T14:24:10.6906760Z 
2023-06-21T14:24:10.6907241Z For more information, try '--help'.
2023-06-21T14:24:11.1345722Z copying path '/nix/store/klp35k5fxxajq3mxbgb1imccpzc3hkhk-stm-hamt-1.2.0.11-doc' from 'https://cache.nixos.org'...
```

On my own machine, this is also reproducible and happens at the end of `nix-shell`:

```
$ nix-shell
[.... lots of stuff ... ]
searching for dependencies of /nix/store/qmhhbs57x699bmmlgjgq94gijkbwkqwi-foundry-0.0.0/bin/.anvil-wrapped
auto-patchelf: 0 dependencies could not be satisfied
running install tests
postAutoPatchelf
error: unrecognized subcommand 'completions'

Usage: chisel [OPTIONS] [COMMAND]

For more information, try '--help'.
error: unrecognized subcommand 'completions'

Usage: chisel [OPTIONS] [COMMAND]

For more information, try '--help'.
error: unrecognized subcommand 'completions'

Usage: chisel [OPTIONS] [COMMAND]

For more information, try '--help'.
```

The return value is still 0 though (weird):

```
[...]
Usage: chisel [OPTIONS] [COMMAND]

For more information, try '--help'.

[nix-shell:~/development/hevm]$ echo $?
0
```

**Comment by msooseth** [comment]
OK, filed an issue regarding the `chisel` errors here: https://github.com/shazow/foundry.nix/issues/22 It's likely due to
```
 ${lib.concatMapStringsSep "\n" (bin: ''
          installShellCompletion --cmd ${bin} --bash <($out/bin/${bin} completions bash) --fish <($out/bin/${bin} completions fish) --zsh <($out/bin/${bin} completions zsh)
        '')
        bins}
    '';
```

in https://github.com/shazow/foundry.nix

I am looking into the actual issue now :D

**Pull request merged**
