### PR TITLE
Add fetchChainIdFrom

### PR DESCRIPTION
**Pull request by arcz**
## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by d-xo** [comment]
what is this for?

**Comment by arcz** [comment]
It's a function to fetch chain id, it was already partially done with `QueryChainId` but this function was missing.

**Comment by arcz** [comment]
@d-xo it is not used by hevm itself but it is useful if you use hevm as a library, I duplicated this function in echidna:
https://github.com/crytic/echidna/blob/bdbf2bba045b7ceffc0fd319839d3737a56f1cbd/lib/Echidna/RPC.hs#L49-L56

**Comment by d-xo** [comment]
got it, thanks!

**Pull request merged**
