### PR TITLE
SymExec: run whole expression simplifier on branch conditions

### PR DESCRIPTION
**Pull request by d-xo**
## Description

Runs the whole expression simplifier on branch conditions. Haven't really benchmarks, but should hopefully help us simplify down some stuff that the inline rules match (e.g. `Eq a a == Lit 1`).

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [x] updated the changelog

### CODE REVIEW

**Comment by msooseth** [comment]
This has now been slightly updated to simplify the conditions that eventually get passed to PleaseAskSMT, which helps in making the preconditions also simplified. I have also added a minor update to the changelog.

**Review by zoep — APPROVED** [review]
Looks good!

**Comment by msooseth** [comment]
Please consider https://github.com/ethereum/hevm/pull/338 -- it is a slightly improved version of this. It can be merged after this without merge conflicts (it builds on top of this).

**Review by msooseth — APPROVED** [review]
lgtm

**Pull request merged**
