### PR TITLE
GHC 9.6 v4 try, with CVC5 this time around.

### PR DESCRIPTION
**Pull request by msooseth**
## Description
Test with CVC5 as default for 

## Checklist

- [ ] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by ggrieco-tob** [comment]
Is CVC5 support coming? I think I tested some time ago and it was broken :thinking:

**Comment by msooseth** [comment]
Yeah, unfortunately you are right. We get: `Array theory solver does not yet support write-chains connecting two different constant arrays` for a single test. I disabled that test for the moment. Just to try.

**Comment by d-xo** [comment]
Awesome to see a green 9.6 finally. I don't love that we have no test coverage for z3 and bitwuzla in ci like this now though.

**Comment by d-xo** [comment]
closing since https://github.com/ethereum/hevm/pull/499 is merged

**Pull request closed without merging**
