### PR TITLE
Prepare 0.51.3 release

### PR DESCRIPTION
**Pull request by arcz**
## Checklist

- [ ] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by msooseth** [comment]
This is experiencing errors due to the bug that's been fixed. Should we try to rebase on top of main?

**Comment by arcz** [comment]
Yes! I’ll rebase

**Comment by msooseth** [comment]
There is apparently one more bug that `unsafeInto` found, triggered here: https://github.com/ethereum/hevm/actions/runs/5530031614/jobs/10088891505 Let me get to the bottom of it. 

```
2023-07-12T09:55:28.0760691Z hevm>       Use --quickcheck-replay=266145 to reproduce.
2023-07-12T09:55:28.0761261Z hevm>       Use -p '/word-simplification/' to rerun this test only.
```

I am working on it :) At least it's reproducible now :smile:

**Comment by msooseth** [comment]
This fixes the issue: #313  Should be merged before release I think. It's regression that I caused with #296

**Pull request merged**
