### PR TITLE
Bump nixpkgs and ethereum tests, use cabal-install from nix

### PR DESCRIPTION
**Pull request by arcz**
## Description
We can now use cabal-install 3.12 from nix

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by msooseth** [comment]
Hahah, I just started working on this, so great!! Thanks, let me see if it goes through, if it does, we'll be golden and hopefully it'll fix the issues we are having with the tstore/mcopy PR!! Thanks so much!

**Comment by msooseth** [comment]
BTW, do you know if we still need this?

```
        # workaround for nixpkgs / ghc / macos / cc issue
        # https://gitlab.haskell.org/ghc/ghc/-/issues/23138
        cc-workaround-ghc-23138 =
          pkgs.writeScriptBin "cc-workaround-ghc-23138" ''
            if [ "$1" = "--print-file-name" ] && [ "$2" = "c++" ]; then
                echo c++
            else
                exec cc "$@"
            fi
          '';
```

What they seem to be saying is that:

```
FYI nixpkgs has now been patched: https://github.com/NixOS/nixpkgs/pull/317224
```

What do you think?

**Comment by arcz** [comment]
I'll check if it's still needed

**Comment by msooseth** [comment]
Well, at least I can reproduce it, which is nice. Lexi says it may be due to static vs dynamic compilation using different GHC.

**Pull request merged**
