### PR TITLE
Remove some underscores from EVM records

### PR DESCRIPTION
**Pull request by arcz**
## Description
Lens are not used for those fields so we can get rid of some underscored without much problem.

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by msooseth** [comment]
Note: This will clash with https://github.com/ethereum/hevm/pull/202 I don't mind fixing the merge conflicts, just an FYI :) 

BTW, can we remove lenses now that we have the `.` notation? That might be more interesting than removing the `_`? Or are these `makeLenses` really needed?

**Comment by d-xo** [comment]
we are still using lenses in some of the EVM records to handle nested updates and so on.

**Comment by msooseth** [comment]
Ah, I see, thanks!

**Comment by d-xo** [comment]
superceded by https://github.com/ethereum/hevm/pull/244

**Pull request closed without merging**
